apiVersion: batch/v1
kind: CronJob
metadata:
  name: hey-ps-cj
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox:1.36
            command: ["echo", "Hello PluralSight!"]
          restartPolicy: Never