---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hey-ps-cj
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            job: hey-ps-cj
        spec:
          containers:
          - name: busybox
            image: busybox:1.36
            args:
            - /bin/sh
            - -c
            - echo "$(date) - Hello PluralSight!"
          restartPolicy: Never

