---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: healthcheck-ds
  namespace: challenge4
  labels:
    app: healthcheck-ds
spec:
  selector:
    matchLabels:
      app: healthcheck-ds
  template:
    metadata:
      labels:
        app: healthcheck-ds
    spec:
      containers:
      - name: healthcheck
        image: busybox:1.36
        command: ['sh', '-c']
        args: "while true; do echo 'HEARTBEAT' > /tmp/k8s-node-status; sleep 2; done"


