---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: healthcheck-ds
  labels:
    app: healthcheck-ds
spec:
  selector:
    matchLabels:
      app: healthcheck-ds
  template:
    metadata:
      labels:
        app: healthcheck-ds
    spec:
      containers:
      - name: healthcheck
        image: busybox:1.36
        command: ['sh', '-c']
        args: ['while true; do echo "$(date) - HEARTBEAT" >> /var/log/k8s-node-status.txt; sleep 2; done']
        volumeMounts:
        - mountPath: /var/log/k8s-node-status.txt
          name: myfile
      volumes:
      - name: myfile
        hostPath:
          path: /var/log/k8s-node-status.txt
          type: FileOrCreate


